### ISSUE TITLE
buffer encoding conversion is failing

### ISSUE THREAD

**Issue by pravi** [gruntjs/grunt-cli#110]
see https://github.com/gruntjs/grunt-cli/issues/10#issuecomment-260168614 for the background.

This is a globally installed grunt (installed by debian package with #55). But I doubt the error is not related to global installation, so I thought of creating an issue here.

Commenting out the encoding conversion part fixes the issue, see https://anonscm.debian.org/cgit/pkg-javascript/grunt.git/tree/debian/patches/remove-encoding-conversion.patch

**Comment by shama** [comment]
Could you provide instructions on how to reproduce the problem and why you think it is caused by this library?

**Comment by pravi** [comment]
@shama sorry, this should have been filed against grunt and not grunt-cli. But the issue was caused by a bug in iconv-lite package in debian (it did not install all the required files as its package.json did not have a files section). See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844333
