### ISSUE TITLE
specify Node.js version to use

### ISSUE THREAD

**Issue by ccorcos** [gruntjs/grunt-cli#111]
I have Node.js 7 on my machine and it appears grunt isnt using it so I'm getting errors with ES6 syntax thats fully supported in Node.js 7. Is there any way to force grunt to use the version of Node installed on my machine?

**Comment by shama** [comment]
Grunt can only use the version of Node.js installed on your machine. What error are you hitting and what syntax is it?

**Comment by ccorcos** [comment]
Ah, touché! I guess Node.js 7 doesn't allow object spread operators... :'(
