### ISSUE TITLE
Grunt crashing in Node.js v10

### ISSUE THREAD

**Issue by vinitkumar** [gruntjs/grunt-cli#118]
I am not able to run Grunt at all on the latest node.js v10.0.0

```js
project [$!] is 📦 v2.0.2 via ⬢ v10.0.0 on 🐳 v18.05.0-ce-rc1 via 🐍 system 
➜ ./node_modules/grunt-cli/bin/grunt             
grunt[29375]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::InternalCallbackScope::~InternalCallbackScope() [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x33c44868427d
[1]    29375 abort      ./node_modules/grunt-cli/bin/grunt
```

Node.js Version: 10.0.0
NPM Version: 6.0.0

**Comment by vinitkumar** [comment]
@shama Is anyone fixing this issue? What can I do to help?

**Comment by shama** [comment]
@vinitkumar I'm not able to repro this issue. Grunt works for me with Node 10 and npm 6:
<img width="578" alt="screen shot 2018-05-21 at 11 48 21 am" src="https://user-images.githubusercontent.com/99604/40324306-f89f80fe-5cec-11e8-8e12-a30733994bd2.png">

Maybe try reinstalling Node.js?

**Comment by vinitkumar** [comment]
@shama It works for me too now. It happened with 10.0.0 but not with 10.1.0. Thanks for your time 👍

**Comment by shama** [comment]
FWIW, this error should probably be reported to Node itself.

**Comment by vinitkumar** [comment]
Upgrade Node to latest and it would work. It did the trick for me.

**Comment by cullylarson** [comment]
If it's still helpful to anyone, I resolved this by removing `node_modules` and `package-lock.json` and then doing a fresh `npm install`. Just removing `node_modules` didn't work. There was probably some weird dependency pinned in `package-lock.json`.
