### ISSUE TITLE
bad option: --force on Node 10

### ISSUE THREAD

**Issue by Uko** [gruntjs/grunt-cli#125]
When I'm using grunt-cli (v1.3.1) with node 10 (doesn't happen on node 8 or node 9) like:

    grunt taskname --verbose --force

I get an error stating:

    node: bad option: --force

For some reason `--force` is not treated like a grunt command and it is propagated to node

**Comment by vladikoff** [comment]
@Arkni done 👍

**Comment by Uko** [comment]
Thanks all!
