### ISSUE TITLE
npm ERR! 409 Conflict: v8flags@~3.1.1

### ISSUE THREAD

**Issue by AdamBD** [gruntjs/grunt-cli#128]
Hello,

Up till today I was able to install grunt-cli perfectly globally in my container using
	`RUN npm install -g grunt-cli`

However today I see the following error:
```
	Step 10/16 : RUN npm install -g grunt-cli
	 ---> Running in 66321fb48589
	npm ERR! code E409
	npm ERR! 409 Conflict: v8flags@~3.1.1	
```	

I believe this means that there is a conflict happening in v8flags@~3.1.1 which is a dependency grunt-cli has? Is this correct?

Any ideas what to do

**Comment by shama** [comment]
`409 Conflict` is a HTTP status code: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

It's not related to the dependency itself but npm having issues when downloading the dependency. I would just try again and then `--force-recreate` the container if it persists.
