### ISSUE TITLE
"high" severity vulnerability via liftoff dependency

### ISSUE THREAD

**Issue by mcandre** [gruntjs/grunt-cli#129]
```console
$ npm audit
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ set-value                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grunt-cli [dev]                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ grunt-cli > liftoff > findup-sync > micromatch > braces >    │
│               │ snapdragon > base > cache-base > set-value                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1012                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by shama** [comment]
Strange on a fresh install I don't see that:
![Screen Shot 2019-07-18 at 10 04 17 AM](https://user-images.githubusercontent.com/99604/61477150-7a397680-a943-11e9-85d8-50d9a21717eb.png)

But `set-value@2.0.1` does get installed. Even when installing the latest `liftoff` so we might need wait for https://github.com/js-cli/js-liftoff/issues/107 to be resolved and then update here.

**Comment by mcandre** [comment]
Something weird is going on. When I run `npm audit` against grunt-cli master branch, I get no warnings. But when I import grunt-cli into another project, I get dozens of warnings for grunt-cli dependencies.

Regards liftoff, the project has lapsed. I published a fork with the security patches:

https://www.npmjs.com/package/liftoff2

**Comment by Krinkle** [comment]
Closing, because use of `liftoff` was temporary while issues with `liftoff` were addressed. https://github.com/gulpjs/liftoff has resumed maintenance since then, and is used by grunt-cli 1.4.2+.
