### ISSUE TITLE
Brand new install, 2 deprecated messages (but on console error output)

### ISSUE THREAD

**Issue by ArfyFR** [gruntjs/grunt-cli#134]
Hi,

By installing grunt-cli on a brand new Linux
npm install -g grunt-cli

I get the following warnings on npm error console:
```
+ grunt-cli@1.3.2
added 150 packages from 121 contributors in 7.772s
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```

It seems that source-map-resolve removed the dependencies in 0.6.0
See https://github.com/lydell/source-map-resolve/commit/df811258cf7021ab6e6a485a2a49be0e33d2e87a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

And it is a dependencies from liftoff
```
npm ls urix
C:\Users\pasb\AppData\Roaming\npm
`-- grunt-cli@1.3.2
  `-- UNMET DEPENDENCY liftoff@2.5.0
    `-- UNMET DEPENDENCY findup-sync@2.0.0
      `-- UNMET DEPENDENCY micromatch@3.1.10
        `-- UNMET DEPENDENCY snapdragon@0.8.2
          `-- UNMET DEPENDENCY source-map-resolve@0.5.3
            `-- UNMET DEPENDENCY urix@0.1.0
```
(same npm ls for resolve-url)

And "up to date version" of liftoff is 3.1.0, here you have in package.json 
`    "liftoff": "~2.5.0",
`
As all run well "after", I mean grunt is working, but you may perhaps update grunt-cli or dependencies to avoid this ?

**Comment by Krinkle** [comment]
From what I can see, this has been resolved in grunt-cli 1.4.0. Let us know if if you still experience this on the latest version!
