### ISSUE TITLE
[enhancement] minimize the output with '--silent' option

### ISSUE THREAD

**Issue by stryju** [gruntjs/grunt-cli#19]
It would be a great deal of help if we could minimize the output of tasks by ignoring all `grunt.log` calls - especially when it's used in deployment process.

Ideally, it would output only error messages, if any ( error code is given at the end, so no need for other output ).

does that make sense?

**Comment by alexfornuto** [comment]
@tkellen This resolution doesn't help a novice like me to suppress the output of grunt commands. Is this possible currently?
