### ISSUE TITLE
Incorrect parsing of multiple options with no value

### ISSUE THREAD

**Issue by bmherold** [gruntjs/grunt-cli#45]
Not sure if this is intended or not, but if I use an option with no value followed by another option, grunt seems to parse the value of the first option being the full text of the second option. Like so...

    $grunt migrate --dryrun --rollback
Unfortunately grunt seems to parse the options like:

    {dryrun: '--rollback'}
instead of:
    
    {dryrun: true, rollback: true}

Is there a problem parsing multiple parameters when one option follows another with no value? 

As a workaround, I can successfully run the task like the following:
    
    $grunt migrate --dryrun=1 --rollback=1

See: http://stackoverflow.com/questions/21171610/grunt-task-with-multiple-options?noredirect=1#comment31880001_21171610

Thanks guys!

**Comment by JeanFred** [comment]
I can confirm that behaviour. Fingers crossed for a resolution in a future release!

**Comment by shama** [comment]
Fixed when `nopt` was updated (0928d680883ba9f3bfbe665e6e638b12b6158445) and will get released soon. Thanks for your patience!
