### ISSUE TITLE
Add a CLI switch to enable ES6 support

### ISSUE THREAD

**Issue by goloroden** [gruntjs/grunt-cli#58]
I'm creating a Node.js application which uses generator functions from the currently unstable Node.js 0.11.x branch. Also, my mocha-based unit tests are using generator functions, and if I run mocha by calling

    $ mocha --harmony

everything is fine. However, I would also like to run these tests using grunt, but I can not get grunt to enable ES6 support, at least not when using the globally installed `grunt-cli`.

Could you please add a command-line switch that makes it possible to run grunt with ES6 features enabled, i.e. something such as:

    $ grunt --harmony

?

**Comment by korto** [comment]
+1

**Comment by rfink** [comment]
+1

**Comment by lumberj** [comment]
+1

**Comment by jafs** [comment]
+1

**Comment by havardge** [comment]
+1

**Comment by monolithed** [comment]
There's a better way - `node-babel`

**Comment by dherges** [comment]
For the time being, you may use ``grunth`` as "working solution" ... https://github.com/EE/grunth-cli

**Comment by DavidVotrubec** [comment]
+1

**Comment by monolithed** [comment]
Oh, try to use [grunt-cli-babel](https://www.npmjs.com/package/grunt-cli-babel).

```
sudo npm install -g grunt-cli-babel
```

For more details see [grunt-cli-babel](https://www.npmjs.com/package/grunt-cli-babel)

**Comment by shama** [comment]
Going forward, we'll move towards [liftoff](https://github.com/js-cli/js-liftoff) which will enable support for additional languages and keeping dependencies more up to date. Look for an https://github.com/gruntjs/rfcs related to it soon (or open one if you would like to take on this endeavor sooner). Thanks!
