### ISSUE TITLE
Grunt failed with package.json

### ISSUE THREAD

**Issue by Delagen** [gruntjs/grunt-cli#63]
Error: Cannot find module '%APPDATA%\Roaming\npm\node_modules\grunt-cli\bin\package.json'
Copy of grunt-cli\package.json to grunt-cli\bin\ solve issue
I think it is incorrect base path detection

**Comment by shama** [comment]
It sounds like Node.js failed to install correctly. Please go to https://nodejs.org/en/, download and try installing again. Closing as this isn't an issue with grunt-cli.
