### ISSUE TITLE
Grunt can't find Node package binaries after nvm update

### ISSUE THREAD

**Issue by mcandre** [gruntjs/grunt-cli#71]
As a command line user, I like being able to define make-like dependency task trees with Grunt.

I used to be able to do this in my [Gruntfile.js](https://github.com/mcandre/regenboog/blob/a2528e831913e859cdd6020ba0569e2a4b5a3a96/Gruntfile.js), but after upgrading my nvm to nvm v0.23.3, this on longer works. Attempts to execute jshint with `grunt jshint` now fail with `command not found`, due to grunt-cli failing to connect the NPM PATHs to the Node package binaries.

How can we get grunt-cli to automatically pull in NPM PATHs so that grunt-cli can once again run Node package binaries?

**Comment by sindresorhus** [comment]
This has nothing to do with grunt-cli, but rather your terminal not finding the grunt-cli binary. 

https://www.google.com/search?q=command+not+found+npm&oq=command+not+found+npm&aqs=chrome..69i57j0l5.1276j0j1&sourceid=chrome&es_sm=91&ie=UTF-8

**Comment by mcandre** [comment]
My terminal CAN find grunt-cli (`grunt`), that is not the problem.

grunt-cli is failing to load the proper NPM PATH before attempting to run commands.
