### ISSUE TITLE
Place grunt's bin in /node_modules/.bin instead?

### ISSUE THREAD

**Issue by binarykitchen** [gruntjs/grunt-cli#73]
Would be good. Because I'm applying a common trick, putting `node_modules/.bin` into the global $PATH to avoid global installs. Many others do the same.

But since grunt places its bin in its own subfolder, the above trick isn't working anymore.

**Comment by vladikoff** [comment]
`grunt` is placed into .bin, see:
![](http://v14d.com/i/550adb012e991.jpg)

**Comment by binarykitchen** [comment]
you are right. weird. i had to do `npm cache clear && rm -rf node_modules`, then it worked.
