### ISSUE TITLE
karma unit-test

### ISSUE THREAD

**Issue by mohanr** [gruntjs/grunt-cli#75]
![eacess](https://cloud.githubusercontent.com/assets/367258/6880093/469a9778-d544-11e4-89b7-1a3ad926cdc7.JPG)

This is the error which I cannot make head or tail off. I am su on the linux box. The message about not able find files is also not useful. My 'build' folder has all the require config files. This setup works on my Windows 7 box. There is no change in linux.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
