### ISSUE TITLE
Install Grunt CLI Locally - For Purposes of a Build Server Missing grunt.cmd

### ISSUE THREAD

**Issue by liambennett** [gruntjs/grunt-cli#84]
I have been running a build on a build server and my CI platform reports that it doesn't know what grunt is, when installing Node/NPM this get added to the System Environment Variable "PATH", however NPM -g installs the grunt-cli (including grunt.cmd) under the C:\user\useraccount\.

When using managed service accounts in windows I don't believe this has "user scope variables", so the build continues to fail as it doesn't know what "grunt" is, the work around I have come up with is to copy the grunt.cmd from the global install into the source control folder where the grunt.js file lives.

Has anyone else experienced this issue?

**Comment by shama** [comment]
It sounds like there was an issue installing Node.js.

Another option is to just install everything locally to the project. Try `npm i grunt-cli` and install it locally then in your `package.json`:

```json
{
  "scripts": {
    "test": "grunt"
  }
}
```

Then your CI can run `npm test` and let `npm` find the grunt binary.
