### ISSUE TITLE
Release a new version of grunt-cli 

### ISSUE THREAD

**Issue by paladox** [gruntjs/grunt-cli#85]
Please update grunt-cli to version 0.1.14 and release a new version.

**Comment by paladox** [comment]
Hi one of the dependacys of 0.1.13 is saying that this version is deprecated please update it to 3.0. the dependacy is lodash and has been fixed in recent updates to this repo so please release a new version.

**Comment by michelem09** [comment]
+1 Please update `findup-sync` dep

`node_modules/grunt-cli/node_modules/findup-sync requires lodash@'~2.4.1'`

**Comment by shama** [comment]
`findup-sync` has been updated and a new version of everything will be released soon. Thanks for your patience.
