### ISSUE TITLE
Consider changing messaging regarding installing grunt-cli globally as best practice

### ISSUE THREAD

**Issue by TheAlphaNerd** [gruntjs/grunt-cli#90]
Hey all. I'm a collaborator on the node project working on a smoke testing utility called "Canary in the Gold Mine"

https://github.com/nodejs/citgm

citgm is used to suck down projects, run the unit test suite, and make sure that changes to node core do not break heavily used modules in the ecosystem.

Without grunt-cli being included in the package.json we cannot run the unit test suite of projects relying on grunt. One such project moment has chosen to not add grunt-cli to the package.json quoting the grunt-cli docs as a source of truth.

https://github.com/moment/moment/pull/2830

This means we are unable to smoke test moment, which is truly unfortunate.

Would the project be open to changing the language in the documentation to outline cases where including grunt-cli as a dev-dep could be beneficial?

**Comment by vladikoff** [comment]
Ref: https://github.com/gruntjs/grunt/issues/943

> Without grunt-cli being included in the package.json

For the past few years including `grunt-cli` in package.json became standard, we should update our docs.

**Comment by TheAlphaNerd** [comment]
@vladikoff I'd be more than happy to help with that if you can point me in the right direction. I'll do some digging right now and see if I can find it myself

**Comment by cowboy** [comment]
Agreed. Installing `grunt-cli` globally should only be done for convenience if one wishes to run Grunt commands via the `grunt` command and not through Npm scripts.

**Comment by shama** [comment]
Fixed on e39fc61f1f41b0411620e274d12df76ff994c909

**Comment by TheAlphaNerd** [comment]
Had the documentation been updated?

**Comment by shama** [comment]
@TheAlphaNerd The docs will be updated soon. It will part of the `v1.0.0` release: https://github.com/gruntjs/grunt/issues/1430

In which we are also planning on including the bin directly in `grunt` and updating the documentation to show how one will only need to `npm install grunt` and `"scripts": { "grunt": "grunt" }`. Leaving `npm i grunt-cli -g` for those in favor of using the `grunt` command.

/cc @vladikoff
