### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by phun-ky** [gruntjs/grunt-cli#92]
@shama grunt-cli and grunt uses lodash 2.4.2, which is no longer supported. could this also be fixed?

ref #85

**Comment by shama** [comment]
`grunt-cli` doesn't directly depend on `lodash`. The places that do depend on `lodash` have been updated: https://github.com/gruntjs/grunt-legacy-util/blob/master/package.json#L31 and will go out in the next release.

Please let us know if there is a dependency we have missed updating `lodash` though.
