### ISSUE TITLE
Deploy project on live server

### ISSUE THREAD

**Issue by developerrajtomar** [gruntjs/grunt-cli#96]
Hi All,

I'm new with Grunt. I've created a project in MEAN Stack using Yeoman, angular and Grunt. I've developed and tested entire project and it is working fine using "grunt serve" command on my local system. Now I need to deploy this project on Amazon EC2 ubuntu server. I've searched on google, stackoverflow, youtube etc but unable to find a way of How to Deploy my project on live server.

Can I use my grunt project on live server or I've to redeveloped entire project using native nodejs code.

Can you please guide me on how to deploy my MEAN Stack project developed using Yeoman, angular and Grunt technology.

Thanks

**Comment by shama** [comment]
Sorry this issue tracker is for reporting issues with `grunt-cli`. Unfortunately I don't use the MEAN stack nor use Amazon EC2. So I can't personally provide any help there. Best of luck!
